bugfix/better context and SDK types
absmartly/react-sdk pull request #20
Opened 2024-03-07 18:41 UTC by calthejuggler

This PR adds better type declarations for the Javascript SDK, allowing for the use of the classes' methods and properties in a more predictable way.

2024-03-07 18:41 UTC, calthejuggler commented
* **#20** <a href="https://app.graphite.dev/github/pr/absmartly/react-sdk/20?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @calthejuggler and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="11px" height="11px"/> <b>Graphite</b></a>
  <!-- Current dependencies on/for this PR: -->

2024-03-08 08:41 UTC, mario-silva approved these changes
LGTM

2024-03-08 08:49 UTC, soma-absmartly requested changes

2024-03-08 08:49 UTC, soma-absmartly commented on src/components/SDKProvider/SDKProvider.tsx
> +    contextOptions: { units: Record<string, any> };
In regards to version bump/backwards compatibility, is this not a breaking change which would require a larger version bump?

2024-03-08 08:49 UTC, soma-absmartly approved these changes
Looking great!

2024-03-08 10:09 UTC, merged